### ISSUE TITLE
漏洞扫描报告执行命令参数出错

### ISSUE THREAD

**Issue by Slsis** [boy-hack/w8scan#2]
python -c"exec(__import__('urllib').urlopen('http://127.0.0.1/w8scan-master/?get/31638683080fb2bce9be21efd3d13adc').read())"
[...] w8scan is working!!!
[...] Initialize engine ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 20, in <module>
  File "<string>", line 6, in <module>
  File "C:\Python27\lib\urllib.py", line 87, in urlopen
    return opener.open(url)
  File "C:\Python27\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "C:\Python27\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "C:\Python27\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\Python27\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\Python27\lib\httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "C:\Python27\lib\ssl.py", line 363, in wrap_socket
    _context=self)
  File "C:\Python27\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:661)
请问问题出在哪啊？

**Comment by boy-hack** [comment]
需要自行在py目录的主程序中加入容错语句，目前没有容错，所以报错会直接返回
